config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
  }

  namespace :user do
    resources :articles
  end
  resources :articles, only: %i[show] do
    resource :favorite, only: %i[create destroy], module: :articles
  end
  resources :users, only: %i[show] do
    resource :following, only: %i[create destroy], module: :users
    resources :followings, only: %i[index], module: :users
  end
  resources :tags, only: %i[index]
  root 'articles#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/article.rb
class Article < ApplicationRecord
  TAG_MAX_SIZE = 5

  belongs_to :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
  validate :tags_must_be_less_than_or_equal_max_size

  scope :default_order, -> { order(created_at: :desc, id: :desc) }
  scope :published, -> { where(published: true) }
  scope :with_tags, ->(tag_names) do
    return all if tag_names.blank?

    joins(:tags).where(tags: { name: tag_names })
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(value)
    new_tags = []
    tag_names = value.split(',').map(&:strip)
    tag_names.each do |tag_name|
      tag = Tag.find_or_create_by(name: tag_name)
      new_tags << tag
    end
    self.tag_ids = new_tags.pluck(:id).uniq # tag_idsでtagging.rbのunique validationに引っかかり例外を吐くのでuniq
  end

  def tags_must_be_less_than_or_equal_max_size
    if tags.size > TAG_MAX_SIZE
      errors.add(:tag_list, "は#{TAG_MAX_SIZE}個までしか登録できません")
    end
  end
end

app/controllers/articles/application_controller.rb
class Articles::ApplicationController < ApplicationController
  before_action :set_article

  private

  def set_article
    @article = Article.published.find(params[:article_id])
  end
end

app/controllers/articles/favorites_controller.rb
class Articles::FavoritesController < Articles::ApplicationController
  before_action :authenticate_user!

  def create
    current_user.favorites.find_or_create_by!(article: @article) # いいね済みの場合は例外を吐かないように
  end

  def destroy
    favorite = current_user.favorites.find_by(article: @article)
    favorite&.destroy # windowを複数開いていいねを解除した時に例外を吐かないように
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.published.with_tags(params[:tag_names]).default_order.page(params[:page])
  end

  def show
    @article = Article.published.find(params[:id])
  end
end

app/controllers/user/articles_controller.rb
class User::ArticlesController < User::ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = current_user.articles.default_order.page(params[:page])
  end

  def show
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to user_article_path(@article), notice: t('controllers.created')
    else
      flash.now[:alert] = t('controllers.failed')
      render :new, status: :unprocessable_content
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to user_article_path(@article), notice: t('controllers.updated')
    else
      flash.now[:alert] = t('controllers.failed')
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @article.destroy!
    redirect_to user_articles_path, notice: t('controllers.destroyed'), status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :published, :tag_list)
  end

  def set_article
    @article = current_user.articles.find(params[:id])
  end
end

app/views/articles/_article.html.haml
.row.p-3
  .col-lg-3
    = render 'users/user', user: article.user
    .d-flex.justify-content-center.align-items-center
      = render 'articles/favorites/favorite', article: article
  .col-lg-9.card
    .card-body
      %header.mb-2.d-flex.justify-content-between
        .articles__author
          = image_tag avatar_path(article.user.avatar), class: 'articles__user-avatar rounded-circle'
          = article.user.name
        .articles__info
          = l article.created_at, format: :date
          - unless article.published?
            %span.badge.bg-secondary 非公開
      .d-flex.justify-content-between
        %h1.fs-2= article.title
        - if article.user == current_user
          %span= link_to '編集する', edit_user_article_path(article), class: 'btn btn-sm btn-outline-secondary'
      .article__tags.mb-2
        - article.tags.each do |tag|
          .badge.text-bg-success= "\##{tag.name}"
      .text-muted.mb-3= "最終更新日：#{ l article.updated_at, format: :date }"
      %article= markdown article.content

app/views/articles/_index.html.haml
= paginate articles

- if articles.present?
  - articles.preload(:tags, user: { avatar_attachment: :blob }).each do |article|
    .card.mb-3.p-2{ class: class_names('bg-dark-subtle': !article.published?) }
      .card-body
        = link_to user_path(article.user), class: 'text-decoration-none text-black' do
          %header.mb-2.d-flex.justify-content-between
            .articles__author
              - if article.user.avatar.attached?
                = image_tag article.user.avatar, class: 'articles__user-avatar rounded-circle'
              = article.user.name
            .articles__info.d-flex
              = l article.created_at, format: :date
        = link_to generate_article_path(article), class: 'text-decoration-none text-black' do
          %h2.fs-4= article.title
          .article__tags.mb-2
            - article.tags.each do |tag|
              .badge.text-bg-success= "\##{tag.name}"
          .text-muted= markdown sanitize(truncate(article.content, escape: false, length: 140))
- else
  記事はありません

= paginate articles

app/views/articles/index.html.haml
%h1.mb-4 記事一覧

= render 'articles/index', articles: @articles

app/views/articles/show.html.haml
= render 'articles/article', article: @article