config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
  }

  namespace :user do
    resources :articles
  end
  resources :articles, only: %i[show] do
    resource :favorite, only: %i[create destroy], module: :articles
  end
  resources :users, only: %i[show] do
    resource :following, only: %i[create destroy], module: :users
    resources :followings, only: %i[index], module: :users
  end
  resources :tags, only: %i[index]
  root 'articles#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :following_user, class_name: 'User', inverse_of: :active_followings
  belongs_to :followed_user, class_name: 'User', inverse_of: :passive_followings

  validates :following_user_id, uniqueness: { scope: :followed_user_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :validatable

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end

  has_many :articles, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_articles, through: :favorites, source: :article
  has_many :active_followings, dependent: :destroy, class_name: 'Following', foreign_key: 'following_user_id', inverse_of: :following_user
  has_many :passive_followings, dependent: :destroy, class_name: 'Following', foreign_key: 'followed_user_id', inverse_of: :followed_user
  has_many :following_users, through: :active_followings, source: :followed_user
  has_many :followed_users, through: :passive_followings, source: :following_user

  validates :name, presence: true

  def favorite?(article)
    self.favorites.find_by(article_id: article.id).present?
  end

  def follow?(user)
    self.active_followings.exists?(followed_user_id: user.id)
  end
end

app/controllers/user/application_controller.rb
class User::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/user/articles_controller.rb
class User::ArticlesController < User::ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = current_user.articles.default_order.page(params[:page])
  end

  def show
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to user_article_path(@article), notice: t('controllers.created')
    else
      flash.now[:alert] = t('controllers.failed')
      render :new, status: :unprocessable_content
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to user_article_path(@article), notice: t('controllers.updated')
    else
      flash.now[:alert] = t('controllers.failed')
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @article.destroy!
    redirect_to user_articles_path, notice: t('controllers.destroyed'), status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :published, :tag_list)
  end

  def set_article
    @article = current_user.articles.find(params[:id])
  end
end

app/controllers/users/application_controller.rb
class Users::ApplicationController < ApplicationController
  before_action :set_user

  private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/followings_controller.rb
class Users::FollowingsController < Users::ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def index
    @following_users = @user.following_users.with_attached_avatar.page(params[:following_page])
    @followed_users = @user.followed_users.with_attached_avatar.page(params[:followed_page])
  end

  def create
    current_user.active_followings.find_or_create_by!(followed_user: @user)
  end

  def destroy
    following = current_user.active_followings.find_by(followed_user: @user)
    following&.destroy!
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name avatar])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles.published.default_order.page(params[:page])
    @favorite_articles = @user.favorite_articles.published.default_order.page(params[:favorites_page])
  end
end

app/views/users/followings/_follow_info.html.haml
- if user_signed_in?
  = turbo_frame_tag 'users-follow' do
    .d-flex.justify-content-center.gap-4.mb-3
      .fw-semibold.text-muted= "#{user.active_followings.count}フォロー"
      .fw-semibold.text-muted= "#{user.passive_followings.count}フォロワー"
    - if current_user != user
      - if current_user.follow?(user)
        = link_to 'フォロー解除', user_following_path(user), class: 'btn btn-outline-secondary w-100', data: { turbo_method: :delete }
      - else
        = link_to 'フォローする', user_following_path(user), class: 'btn btn-outline-secondary w-100', data: { turbo_method: :post }
- else
  .d-flex.justify-content-center.gap-4.mb-3
    .fw-semibold.text-muted= "#{user.active_followings.count}フォロー"
    .fw-semibold.text-muted= "#{user.passive_followings.count}フォロワー"
  = link_to 'フォローする', user_following_path(user), class: 'btn btn-outline-secondary w-100', data: { turbo_method: :post }

app/views/users/followings/_followed_users.html.haml
= paginate followed_users, param_name: :followed_page

- if followed_users.present?
  - followed_users.each do |user|
    = link_to user_path(user), class: 'text-decoration-none' do
      .card.mb-3.p-2
        .card-body
          %header
            = image_tag avatar_path(user.avatar), class: 'followed_users__user-avatar rounded-circle'
            = user.name
- else
  .card.mb-3.p-2
    .card-body フォローされている人がいません

= paginate followed_users, param_name: :followed_page

app/views/users/followings/_following_users.html.haml
= paginate following_users, param_name: :following_page

- if following_users.present?
  - following_users.each do |user|
    = link_to user_path(user), class: 'text-decoration-none' do
      .card.mb-3.p-2
        .card-body
          %header
            = image_tag avatar_path(user.avatar), class: 'following_users__user-avatar rounded-circle'
            = user.name
- else
  .card.mb-3.p-2
    .card-body フォローしている人がいません

= paginate following_users, param_name: :following_page

app/views/users/followings/_users_follow.html.haml
- if user_signed_in?
  = turbo_frame_tag 'users-follow' do
    .d-flex.justify-content-center.gap-4.mb-3
      .fw-semibold= link_to "#{user.active_followings.count}フォロー", user_followings_path(user), data: { turbo: false }, class: 'text-decoration-none text-muted'
      .fw-semibold= link_to "#{user.passive_followings.count}フォロワー", user_followings_path(user, followed_page: 1), data: { turbo: false }, class: 'text-decoration-none text-muted'
    - if current_user != user
      - if current_user.follow?(user)
        = link_to 'フォロー解除', user_following_path(user), class: 'btn btn-outline-secondary w-100', data: { turbo_method: :delete }
      - else
        = link_to 'フォローする', user_following_path(user), class: 'btn btn-outline-secondary w-100', data: { turbo_method: :post }
- else
  .d-flex.justify-content-center.gap-4.mb-3
    .fw-semibold.text-muted= "#{user.active_followings.count}フォロー"
    .fw-semibold.text-muted= "#{user.passive_followings.count}フォロワー"
  = link_to 'フォローする', user_following_path(user), class: 'btn btn-outline-secondary w-100', data: { turbo_method: :post }

app/views/users/followings/create.html.haml
= render 'users/followings/users_follow', user: @user

app/views/users/followings/destroy.html.haml
= render 'users/followings/users_follow', user: @user

app/views/users/followings/index.html.haml
%h1="#{@user.name}のフォローリスト"

%nav.mb-3
  .nav.nav-tabs{:role => "tablist"}
    %button.nav-link{class: class_names(active: params[:followed_page].blank?), data: {"bs-target": ".nav-following-users", "bs-toggle": "tab"}, :role => "tab", :type => "button"} フォローしているユーザー
    %button.nav-link{class: class_names(active: params[:followed_page].present?), data: {"bs-target": ".nav-followed-users", "bs-toggle": "tab"}, :role => "tab", :type => "button"} フォローされているユーザー
.tab-content
  .nav-following-users.tab-pane.fade{class: class_names('show active': params[:followed_page].blank?), role: "tabpanel", tabindex: "0"}
    = render 'users/followings/following_users', following_users: @following_users
  .nav-followed-users.tab-pane.fade{class: class_names('show active': params[:followed_page].present?), role: "tabpanel", tabindex: "0"}
    = render 'users/followings/followed_users', followed_users: @followed_users