config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
  }

  namespace :user do
    resources :articles
  end
  resources :articles, only: %i[show] do
    resource :favorite, only: %i[create destroy], module: :articles
  end
  resources :users, only: %i[show] do
    resource :following, only: %i[create destroy], module: :users
    resources :followings, only: %i[index], module: :users
  end
  resources :tags, only: %i[index]
  root 'articles#index'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.bg-body-tertiary
  .container-fluid
    = link_to 'QiitaClone', root_path, class: 'navbar-brand'
    %button.navbar-toggler{ data: { bs_target: '#navbarNavDropdown', bs_toggle: 'collapse' }, type: 'button' }
      %span.navbar-toggler-icon
    #navbarNavDropdown.collapse.navbar-collapse
      %ul.navbar-nav
        %li.nav-item
          = link_to 'タグ一覧', tags_path, class: 'nav-link'
        %li.nav-item
          = link_to '記事投稿', new_user_article_path, class: 'nav-link'
        %li.nav-item.dropdown
          - if user_signed_in?
            %a.nav-link.dropdown-toggle{ 'data-bs-toggle': 'dropdown', href: '#', role: 'button' }
              = image_tag avatar_path(current_user.avatar), class: 'header__users-avatar rounded-circle'
              = current_user.name
            %ul.dropdown-menu
              %li
                = link_to '自分の記事一覧', user_articles_path, class: 'dropdown-item'
              %li
                = link_to 'マイページ', user_path(current_user), class: 'dropdown-item'
              %li
                = link_to '基本情報編集', edit_user_registration_path, class: 'dropdown-item'
              %hr
              %li
                = link_to 'ログアウト', destroy_user_session_path, class: 'dropdown-item', data: { turbo_method: :delete }
          - else
            %a.nav-link.dropdown-toggle{ 'data-bs-toggle': 'dropdown', href: '#', role: 'button' } ログイン
            %ul.dropdown-menu
              %li
                = link_to '新規登録', new_user_registration_path, class: 'dropdown-item'
              %li
                = link_to 'ログイン', new_user_session_path, class: 'dropdown-item'

app/views/layouts/_toast.html.haml
- if notice.present? || alert.present?
  .position-fixed.top-0.end-0.m-2.z-1
    .toast.show
      .toast-header
        %strong.me-auto QiitaClone
        %button.btn-close{ 'data-bs-dismiss': 'toast', type: 'button' }
      .toast-body
        - if notice
          .text-success
            = notice
        - else
          .text-danger
            = alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }
    %title QiitaCloneApp
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  %body
    = render 'layouts/toast'
    = render 'layouts/header'
    .container
      = yield